baseURL = "https://msalcantara.github.io/"
languageCode = "en-us"
title = "Matheus Alcantara"
theme="hermit"
publishDir="docs"


[author]
  name = "matheusssilv97@gmail.com"

[params]
  themeColor = "#494f5c"

  # homeSubtitle = ""

  [[params.social]]
    name = "github"
    url = "https://github.com/msAlcantara"

  [[params.social]]
    name = "email"
    url = "mailto:matheusssilv97@gmail.com"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/matheus-alcantara/"

[menu]

  [[menu.main]]
    name = "cv"
    url = "cv/"
    weight = 10
