languageCode = "en-us"
baseURL = "https://msalcantara.github.io/"
title = "Matheus Alcantara"
theme="PaperMod"
publishDir="docs"
DefaultContentLanguage = "en"

[author]
  name = "matheusssilv97@gmail.com"

[params]
    defaultTheme = "auto"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/msAlcantara"

    [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/matheussilv__"

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/matheus-alcantara/?locale=en_US"

[languages]
    [languages.en]
        [languages.en.params.profileMode]
            enabled = true
            title = "Hi, I'm Matheus"
            subtitle = ""

            [[languages.en.params.profileMode.buttons]]
            name = "Posts"
            url = "/posts"
            [[languages.en.params.profileMode.buttons]]
            name = "About"
            url = "/about"

        [[languages.en.menu.main]]
        identifier = "posts"
        name       = "Posts"
        url        = "/posts"

        [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
