languageCode = "en-us"
baseURL = "https://msalcantara.github.io/"
title = "Matheus Alcantara"
theme="hermit"
publishDir="docs"
DefaultContentLanguage = "en"


[author]
  name = "matheusssilv97@gmail.com"


[languages]
    [languages.en]
        [languages.en.params]
        themeColor = "#494f5c"

        [[languages.en.params.social]]
        name = "github"
        url = "https://github.com/msAlcantara"

        [[languages.en.params.social]]
        name = "email"
        url = "mailto:matheusssilv97@gmail.com"

        [[languages.en.params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/matheus-alcantara/?locale=en_US"

        [[languages.en.menu.main]]
        name = "cv"
        url = "cv/"
        weight = 10
