languageCode = "en-us"
baseURL = "https://mattheusv.github.io/"
title = "Matheus Alcantara"
theme="PaperMod"
publishDir="docs"
DefaultContentLanguage = "en"

[author]
  name = "matheusssilv97@gmail.com"

[params]
    defaultTheme = "auto"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mattheusv"

    [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/mattheusv__"

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/matheus-alcantara/?locale=en_US"

[params.meta]
    favicon = false

[languages]
    [languages.en]
        [languages.en.params.profileMode]
            enabled = true
            title = "Hi, I'm Matheus"
            subtitle = ""

            [[languages.en.params.profileMode.buttons]]
            name = "Notes"
            url = "/notes"
            [[languages.en.params.profileMode.buttons]]
            name = "About"
            url = "/about"

        [[languages.en.menu.main]]
        identifier = "notes"
        name       = "Notes"
        url        = "/notes"

        [[languages.en.menu.main]]
        identifier = "papers"
        name = "Papers"
        url = "/papers"

        [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
